version: '3.8'
name: population
services:

  backend:
    container_name: population_backend
    build: 
      context: ./backend
    environment:
      - DATABASE_HOST=population_database
    ports:
      - 4000:4000

  database:
    container_name: population_database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: population
      # Use trust auth to simplify usage as this db is used only in local connections
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432

